import { describe, expect, it } from 'vitest';
import { loadBoard, type Board } from './board';
import { canOverwriteBoardMd, PLACEHOLDER_MARKER, renderBoardMd, sortForBoardMd, yearOf } from './boardmd';
import type { Card } from './card';
import { GENERATED_MARKER } from './manifest';
import { FIXTURE_VAULT, readerOf, readFixture, snapshotOf } from './test-helpers';

const snapshot = snapshotOf(FIXTURE_VAULT);
const read = readerOf(FIXTURE_VAULT);

function card(over: Partial<Card> & { id: string; path: string }): Card {
	const [prefix, n] = over.id.split('-');
	return {
		prefix: prefix ?? '',
		number: Number(n),
		title: over.id,
		state: 'todo',
		column: 'backlog',
		type: null,
		summary: null,
		created: null,
		updated: null,
		links: [],
		shape: 'frontmatter',
		entries: null,
		...over,
	};
}

describe('BOARD.md (BOARD_FORMAT.md §3, pinned 2026-09-07)', () => {
	it('renders the board-plugin board in the pinned shape', async () => {
		const board = await loadBoard({ dir: 'board-plugin/board', manifestPath: 'board-plugin/board/board.json' }, snapshot, read);
		expect(renderBoardMd(board)).toBe(`<!-- generated by pangolin-board; do not edit -->
# board-plugin — Board

> Card ids: \`KB-N\`. Generated from \`board.json\` and the cards; edit those, not this file.

## Backlog

| Card | Summary | Updated |
|---|---|---|
| [KB-2](backlog/KB-2-render-the-board-view-with-drag-between-columns.md) | Render the board view with drag between columns | 2026-09-07 |
| [KB-1](backlog/KB-1-read-a-board-directory-into-a-model.md) | Read a board directory into a model | 2026-09-07 |

## In progress

| Card | Summary | Updated |
|---|---|---|
| _none_ | — | — |

## Done

| Card | Summary | Updated |
|---|---|---|
| _none_ | — | — |
`);
	});

	it('splits a {year} column by year, newest first, and prefers summary over title', () => {
		const base: Board = {
			dir: 'p/board',
			manifestPath: null,
			hasManifest: false,
			writable: true,
			manifest: {
				id: 'p',
				title: 'p',
				prefix: 'PP',
				prefixes: [],
				next: 1,
				provider: 'pangolin-board',
				columns: [
					{ dir: 'backlog', title: 'Backlog', state: 'todo' },
					{ dir: 'done/{year}', title: 'Done', state: 'done' },
				],
			},
			cards: [
				card({ id: 'PP-1', path: 'p/board/done/2025/PP-1-old.md', column: 'done/{year}', state: 'done', updated: '2025-12-01', title: 'Old' }),
				card({ id: 'PP-3', path: 'p/board/done/2026/PP-3-new.md', column: 'done/{year}', state: 'done', updated: '2026-02-01', title: 'A | B', summary: 'Pipe | here' }),
				card({ id: 'PP-2', path: 'p/board/done/2026/PP-2-mid.md', column: 'done/{year}', state: 'done', updated: '2026-02-01', title: 'Mid' }),
			],
		};
		expect(renderBoardMd(base)).toBe(`<!-- generated by pangolin-board; do not edit -->
# p — Board

> Card ids: \`PP-N\`. Generated from \`board.json\` and the cards; edit those, not this file.

## Backlog

| Card | Summary | Updated |
|---|---|---|
| _none_ | — | — |

## Done

### 2026

| Card | Summary | Updated |
|---|---|---|
| [PP-3](done/2026/PP-3-new.md) | Pipe \\| here | 2026-02-01 |
| [PP-2](done/2026/PP-2-mid.md) | Mid | 2026-02-01 |

### 2025

| Card | Summary | Updated |
|---|---|---|
| [PP-1](done/2025/PP-1-old.md) | Old | 2025-12-01 |
`);
		const done = base.manifest.columns[1];
		if (!done) throw new Error('column');
		expect(yearOf(base, done, base.cards[0] as Card)).toBe('2025');
	});

	it('orders by updated desc, then number desc, then id, with unknown dates last', () => {
		const sorted = sortForBoardMd([
			card({ id: 'A-1', path: 'x/A-1.md', updated: '2026-01-01' }),
			card({ id: 'A-2', path: 'x/A-2.md', updated: null }),
			card({ id: 'A-3', path: 'x/A-3.md', updated: '2026-03-01' }),
			card({ id: 'A-4', path: 'x/A-4.md', updated: '2026-03-01' }),
		]).map((c) => c.id);
		expect(sorted).toEqual(['A-4', 'A-3', 'A-1', 'A-2']);
	});

	it('overwrites only generated or placeholder files', () => {
		expect(canOverwriteBoardMd(null)).toBe(true);
		expect(canOverwriteBoardMd(`${GENERATED_MARKER}\n# x`)).toBe(true);
		expect(canOverwriteBoardMd(`${PLACEHOLDER_MARKER}\n# x`)).toBe(true);
		expect(canOverwriteBoardMd(readFixture('board-plugin/board/BOARD.md'))).toBe(true);
		expect(canOverwriteBoardMd(readFixture('audiovisual/board/BOARD.md'))).toBe(false);
	});
});
