/**
 * `board.json` (BOARD_FORMAT.md §1) and the default columns used when a
 * directory has no manifest.
 */

export type CardState = 'todo' | 'in_progress' | 'done';

export const STATES: readonly CardState[] = ['todo', 'in_progress', 'done'];

export interface BoardColumn {
	/** Directory below the board, possibly with a `{year}` placeholder. */
	dir: string;
	title: string;
	state: CardState;
}

export interface BoardManifest {
	id: string;
	title: string;
	prefix: string;
	next: number;
	provider: string;
	columns: BoardColumn[];
}

export const DEFAULT_COLUMNS: readonly BoardColumn[] = [
	{ dir: 'backlog', title: 'Backlog', state: 'todo' },
	{ dir: 'wip', title: 'WIP', state: 'in_progress' },
	{ dir: 'done/{year}', title: 'Done', state: 'done' },
];

export const GENERATED_MARKER = '<!-- generated by pangolin-board; do not edit -->';

/** Parse `board.json`; returns null when the text is not a usable manifest. */
export function parseManifest(text: string): BoardManifest | null {
	let raw: unknown;
	try {
		raw = JSON.parse(text);
	} catch {
		return null;
	}
	if (!raw || typeof raw !== 'object') return null;
	const obj = raw as Record<string, unknown>;
	const columns = Array.isArray(obj.columns) ? obj.columns.map(parseColumn).filter((c): c is BoardColumn => c !== null) : [];
	const prefix = typeof obj.prefix === 'string' ? obj.prefix : '';
	const next = typeof obj.next === 'number' && Number.isInteger(obj.next) && obj.next > 0 ? obj.next : 1;
	return {
		id: typeof obj.id === 'string' ? obj.id : '',
		title: typeof obj.title === 'string' ? obj.title : '',
		prefix,
		next,
		provider: typeof obj.provider === 'string' ? obj.provider : 'pangolin-board',
		columns: columns.length > 0 ? columns : [...DEFAULT_COLUMNS],
	};
}

function parseColumn(raw: unknown): BoardColumn | null {
	if (!raw || typeof raw !== 'object') return null;
	const obj = raw as Record<string, unknown>;
	if (typeof obj.dir !== 'string' || obj.dir === '') return null;
	const dir = obj.dir.replace(/^\/+|\/+$/g, '');
	const state = STATES.find((s) => s === obj.state) ?? 'todo';
	const title = typeof obj.title === 'string' && obj.title !== '' ? obj.title : humanizeDir(dir);
	return { dir, title, state };
}

/** `wip` → `WIP`, `done/{year}` → `Done`, `in-review` → `In review`. */
export function humanizeDir(dir: string): string {
	const leaf = dir.replace(/\/\{year\}$/, '').split('/').pop() ?? dir;
	if (leaf.toLowerCase() === 'wip') return 'WIP';
	const words = leaf.replace(/[-_]+/g, ' ');
	return words.charAt(0).toUpperCase() + words.slice(1);
}

/** Write `next` back into the manifest text, touching nothing else. */
export function withNext(text: string, next: number): string {
	const replaced = text.replace(/("next"\s*:\s*)\d+/, `$1${next}`);
	if (replaced !== text) return replaced;
	// No `next` key yet: add one after `prefix`, or at the top.
	if (/"prefix"\s*:\s*"[^"]*"\s*,?/.test(text)) {
		return text.replace(/("prefix"\s*:\s*"[^"]*")/, `$1,\n  "next": ${next}`);
	}
	return text.replace(/^\s*\{/, `{\n  "next": ${next},`);
}

/** Regex matching a column directory (relative to the board), `{year}` as four digits. */
export function columnDirPattern(column: BoardColumn): RegExp {
	const escaped = column.dir.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\\\{year\\\}/g, '\\d{4}');
	return new RegExp(`^${escaped}$`);
}

/** The concrete directory a card moved into this column lands in. */
export function resolveColumnDir(column: BoardColumn, today: string): string {
	return column.dir.replace(/\{year\}/g, today.slice(0, 4));
}

/** Find the column a relative directory belongs to, tolerant of resolved `{year}` paths. */
export function columnForDir(columns: readonly BoardColumn[], relativeDir: string): BoardColumn | undefined {
	return columns.find((c) => c.dir === relativeDir || columnDirPattern(c).test(relativeDir));
}

/** Manifest for a directory without one: the default columns, titled after the directory. */
export function defaultManifest(boardDir: string, prefix: string): BoardManifest {
	const segments = boardDir.split('/').filter(Boolean);
	const leaf = segments[segments.length - 1] ?? '';
	const title = leaf === 'board' && segments.length > 1 ? (segments[segments.length - 2] ?? leaf) : leaf || 'Board';
	return { id: title, title, prefix, next: 1, provider: 'pangolin-board', columns: [...DEFAULT_COLUMNS] };
}
